/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quadrado.h"

int *
calcquadrado_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	printf("Funcao quadrado foi chamada para o numero (%d)\n", argp->a);

	result = argp->a * argp->a;

	return &result;
}
