/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define somar 1
extern  int * somar_1(numbers *, CLIENT *);
extern  int * somar_1_svc(numbers *, struct svc_req *);
#define sub 2
extern  int * sub_1(numbers *, CLIENT *);
extern  int * sub_1_svc(numbers *, struct svc_req *);
#define mult 3
extern  int * mult_1(numbers *, CLIENT *);
extern  int * mult_1_svc(numbers *, struct svc_req *);
#define div 4
extern  int * div_1(numbers *, CLIENT *);
extern  int * div_1_svc(numbers *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define somar 1
extern  int * somar_1();
extern  int * somar_1_svc();
#define sub 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define mult 3
extern  int * mult_1();
extern  int * mult_1_svc();
#define div 4
extern  int * div_1();
extern  int * div_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
