/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
add_prog_1(char *host, int x, int y)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  somar_1_arg;
	int  *result_2;
	numbers  sub_1_arg;
	int  *result_3;
	numbers  mult_1_arg;
	int  *result_4;
	numbers  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	somar_1_arg.a=x;
	somar_1_arg.b=y;

	sub_1_arg.a=x;
	sub_1_arg.b=y;
	
	mult_1_arg.a=x;
	mult_1_arg.b=y;

	div_1_arg.a=x;
	div_1_arg.b=y;

	result_1 = somar_1(&somar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
		printf("Resultado da soma: %d\n", *result_1);	
	}
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
		printf("Resultado da subtracao: %d\n", *result_2);	
	}
	result_3 = mult_1(&mult_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
		printf("Resultado da multiplicacao: %d\n", *result_3);	
	}
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
		printf("Resultado da divisao: %d\n", *result_4);	
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host, atoi(argv[2]), atoi(argv[3]));
exit (0);
}
