/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *somar_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Funcao soma foi chamada (%d,%d)\n", argp->a, argp->b);

	result = argp->a + argp->b;

	return &result;
}

int *sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Funcao subtracao foi chamada (%d,%d)\n", argp->a, argp->b);

	if(argp->a > argp->b){
		result = argp->a - argp->b;
	}else{
		result = argp->a - argp->b;
	}


	return &result;
}

int *mult_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Funcao multiplicacao foi chamada (%d,%d)\n", argp->a, argp->b);

	result = argp->a * argp->b;

	return &result;
}

int *div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Funcao divisao foi chamada (%d,%d)\n", argp->a, argp->b);

	if(argp->b == 0){
		printf("Error: Divisao por zero\n");
		result = 0.0;
	}else{
		result = (double)argp->a / argp->b;
	}

	return &result;
}
